messages:
  warmup-end-message: "<red>Warmup time finished. The PvP is now enabled!"
  join-game-message: "<aqua>Place the join message here"
  bossbar-waiting-message: "<green>%time% seconds or %remaining_players% to start the game."
  starting-phase-message: "<blue>The game will start in 15 seconds, be prepared..."
  killed-by-player-message: "<white>%killer% <yellow>eliminated <red>%victim%<yellow>."

#Waiting time to change to starting phase if minimum-players is reached
waiting-time: 120
#Minimum players required to start a game
minimum-players: 4
#Starting time phase time
starting-time: 15
#Skip to starting phase if that amount of players is reached
skip-to-start-with: 6
